name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"      # roda a cada 12h
  workflow_dispatch:             # permite rodar manualmente no botão Run workflow
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      # Faz checkout do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Gera o SVG do Pac-Man
      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: gmourazz

      # Prepara os arquivos dentro da pasta dist/ para publicar
      - name: Prepare artifacts
        run: |
          mkdir -p dist
          cp pacman-contribution-graph*.svg dist/ 2>/dev/null || true
          cp -r output/* dist/ 2>/dev/null || true
          echo "::group::Dist listing"; ls -la dist || true; echo "::endgroup::"

      # Publica o conteúdo na branch "output"
      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
